import React from 'react';
import { Download, Share2, ArrowRight, Check, Sparkles, Navigation, Clock, FlaskConical } from 'lucide-react';
import InteractiveMap from './InteractiveMap';
import RiskScoreCard from './RiskScoreCard';
import VehicleProfileCard from './VehicleProfileCard';

export default function RouteAnalysisResults({
  routeData,
  selectedVehicle,
  focusedHazard,
  onSelectHazard,
  onOpenReport,
  onShareRoute,
  onSelectAlternativeRoute,
  activeRouteIndex,
  copiedLink,
  darkMode,
  mapsKey,
  isAnalyzing
}) {
  const alternativeRoutes = routeData.alternativeRoutes || [];

  return (
    <section className={`route-results-section ${isAnalyzing ? 'results-stale' : ''}`} id="results-view">
      {/* Results Header Bar */}
      <div className="results-header-row">
        <div className="results-meta-col">
          <div className="results-title-badge-wrap">
            <h2 className="results-main-title">Route Analysis Results</h2>
            {routeData.isSample && (
              <span className="sample-badge" title="Pre-computed example. Run an analysis above to see live results.">
                <FlaskConical size={12} /> Sample data
              </span>
            )}
            {routeData.isDemo && (
              <span className="sample-badge" title="Generated by the offline demo engine, not YOLOv8.">
                <FlaskConical size={12} /> Demo mode
              </span>
            )}
            {alternativeRoutes.length > 1 && (
              <span className="routes-count-badge">
                {alternativeRoutes.length} Alternative Routes Evaluated
              </span>
            )}
          </div>
          <div className="results-breadcrumbs">
            <span className="location-start-tag">{routeData.startLocation}</span>
            <ArrowRight size={14} className="breadcrumb-arrow" />
            <span className="location-dest-tag">{routeData.destination}</span>
          </div>
          <div className="results-timestamp">
            {routeData.isSample ? 'Example route — ' : 'Analyzed on '}{routeData.timestamp}
            {routeData.routeSummary ? ` · via ${routeData.routeSummary}` : ''}
          </div>
        </div>

        {/* Action Buttons */}
        <div className="results-actions-group">
          <button
            type="button"
            className="btn-action-primary"
            onClick={onOpenReport}
            title="Open printable hazard report"
          >
            <Download size={16} />
            <span>Download Report</span>
          </button>

          <button
            type="button"
            className="btn-action-outline"
            onClick={onShareRoute}
            title="Copy a link to this route"
          >
            {copiedLink ? (
              <>
                <Check size={16} className="text-success" />
                <span>Link Copied!</span>
              </>
            ) : (
              <>
                <Share2 size={16} />
                <span>Share</span>
              </>
            )}
          </button>
        </div>
      </div>

      {/* Alternative Routes Comparison Selector Bar */}
      {alternativeRoutes.length > 1 && (
        <div className="alternative-routes-container">
          <div className="alt-routes-header">
            <span className="alt-routes-title">Select Route Option to Compare:</span>
          </div>

          <div className="alt-routes-grid">
            {alternativeRoutes.map((alt, idx) => {
              const isSelected = (activeRouteIndex === idx);
              const isRecommended = alt.is_recommended;
              const score = alt.overall_score;

              return (
                <button
                  key={idx}
                  type="button"
                  className={`alt-route-card-btn ${isSelected ? 'alt-route-active' : ''} ${isRecommended ? 'alt-route-recommended' : ''}`}
                  onClick={() => onSelectAlternativeRoute(idx)}
                  aria-pressed={isSelected}
                >
                  <div className="alt-route-top-row">
                    <div className="alt-route-name">
                      <strong>Route {idx + 1}:</strong> {alt.summary}
                    </div>
                    {isRecommended && (
                      <span className="recommended-badge">
                        <Sparkles size={13} />
                        <span>Recommended</span>
                      </span>
                    )}
                  </div>

                  <div className="alt-route-meta-row">
                    <div className="alt-meta-tag">
                      <Navigation size={13} />
                      <span>{alt.distance_km} km</span>
                    </div>
                    {alt.duration_min != null && (
                      <div className="alt-meta-tag">
                        <Clock size={13} />
                        <span>{alt.duration_min} min</span>
                      </div>
                    )}
                    <div className="alt-meta-tag">
                      <span>{alt.hazard_count} hazards</span>
                    </div>
                    <div className={`alt-risk-pill ${score >= 70 ? 'pill-high' : score >= 45 ? 'pill-med' : 'pill-low'}`}>
                      Risk: {score}/100
                    </div>
                  </div>
                </button>
              );
            })}
          </div>
        </div>
      )}

      {/* Main Grid: Left Map + Right Stats/Vehicle */}
      <div className="results-dashboard-grid">
        <div className="dashboard-map-panel">
          <InteractiveMap
            routeData={routeData}
            focusedHazard={focusedHazard}
            onSelectHazard={onSelectHazard}
            onSelectRoute={onSelectAlternativeRoute}
            darkMode={darkMode}
            mapsKey={mapsKey}
          />
        </div>

        <div className="dashboard-stats-panel">
          <RiskScoreCard routeData={routeData} />
          <VehicleProfileCard vehicle={selectedVehicle} />
        </div>
      </div>
    </section>
  );
}
